# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gyroYaw.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgyroYaw.proto\x12\ngameEngine\"\x16\n\x07GyroYaw\x12\x0b\n\x03yaw\x18\x01 \x02(\x02')



_GYROYAW = DESCRIPTOR.message_types_by_name['GyroYaw']
GyroYaw = _reflection.GeneratedProtocolMessageType('GyroYaw', (_message.Message,), {
  'DESCRIPTOR' : _GYROYAW,
  '__module__' : 'gyroYaw_pb2'
  # @@protoc_insertion_point(class_scope:gameEngine.GyroYaw)
  })
_sym_db.RegisterMessage(GyroYaw)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GYROYAW._serialized_start=29
  _GYROYAW._serialized_end=51
# @@protoc_insertion_point(module_scope)