# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pacmanDirection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pacmanDirection.proto\x12\ngameEngine\"~\n\x0fPacmanDirection\x12\x38\n\tdirection\x18\x01 \x02(\x0e\x32%.gameEngine.PacmanDirection.Direction\"1\n\tDirection\x12\x08\n\x04STOP\x10\x04\x12\x05\n\x01W\x10\x00\x12\x05\n\x01\x41\x10\x01\x12\x05\n\x01S\x10\x02\x12\x05\n\x01\x44\x10\x03')



_PACMANDIRECTION = DESCRIPTOR.message_types_by_name['PacmanDirection']
_PACMANDIRECTION_DIRECTION = _PACMANDIRECTION.enum_types_by_name['Direction']
PacmanDirection = _reflection.GeneratedProtocolMessageType('PacmanDirection', (_message.Message,), {
  'DESCRIPTOR' : _PACMANDIRECTION,
  '__module__' : 'pacmanDirection_pb2'
  # @@protoc_insertion_point(class_scope:gameEngine.PacmanDirection)
  })
_sym_db.RegisterMessage(PacmanDirection)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PACMANDIRECTION._serialized_start=37
  _PACMANDIRECTION._serialized_end=163
  _PACMANDIRECTION_DIRECTION._serialized_start=114
  _PACMANDIRECTION_DIRECTION._serialized_end=163
# @@protoc_insertion_point(module_scope)